// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: admin_rest_proto.proto

package protobuf_admin_rest

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProtoID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ProtoID) Reset() {
	*x = ProtoID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_rest_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoID) ProtoMessage() {}

func (x *ProtoID) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rest_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoID.ProtoReflect.Descriptor instead.
func (*ProtoID) Descriptor() ([]byte, []int) {
	return file_admin_rest_proto_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoID) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ProtoImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ImagePath string `protobuf:"bytes,2,opt,name=ImagePath,proto3" json:"ImagePath,omitempty"`
}

func (x *ProtoImage) Reset() {
	*x = ProtoImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_rest_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoImage) ProtoMessage() {}

func (x *ProtoImage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rest_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoImage.ProtoReflect.Descriptor instead.
func (*ProtoImage) Descriptor() ([]byte, []int) {
	return file_admin_rest_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoImage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProtoImage) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

type ProtoRestaurant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          uint64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ManagerID   uint64  `protobuf:"varint,2,opt,name=ManagerID,proto3" json:"ManagerID,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Rating      float32 `protobuf:"fixed32,5,opt,name=Rating,proto3" json:"Rating,omitempty"`
	ImagePath   string  `protobuf:"bytes,6,opt,name=ImagePath,proto3" json:"ImagePath,omitempty"`
}

func (x *ProtoRestaurant) Reset() {
	*x = ProtoRestaurant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_rest_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoRestaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoRestaurant) ProtoMessage() {}

func (x *ProtoRestaurant) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rest_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoRestaurant.ProtoReflect.Descriptor instead.
func (*ProtoRestaurant) Descriptor() ([]byte, []int) {
	return file_admin_rest_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoRestaurant) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProtoRestaurant) GetManagerID() uint64 {
	if x != nil {
		return x.ManagerID
	}
	return 0
}

func (x *ProtoRestaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoRestaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtoRestaurant) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProtoRestaurant) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

type ProtoProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price     float32 `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	ImagePath string  `protobuf:"bytes,4,opt,name=ImagePath,proto3" json:"ImagePath,omitempty"`
	RestID    uint64  `protobuf:"varint,5,opt,name=RestID,proto3" json:"RestID,omitempty"`
	Tag       uint64  `protobuf:"varint,6,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *ProtoProduct) Reset() {
	*x = ProtoProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_rest_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoProduct) ProtoMessage() {}

func (x *ProtoProduct) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rest_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoProduct.ProtoReflect.Descriptor instead.
func (*ProtoProduct) Descriptor() ([]byte, []int) {
	return file_admin_rest_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoProduct) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProtoProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoProduct) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProtoProduct) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *ProtoProduct) GetRestID() uint64 {
	if x != nil {
		return x.RestID
	}
	return 0
}

func (x *ProtoProduct) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type ProtoPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      uint64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Address string  `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Radius  float32 `protobuf:"fixed32,3,opt,name=Radius,proto3" json:"Radius,omitempty"`
	RestID  uint64  `protobuf:"varint,4,opt,name=RestID,proto3" json:"RestID,omitempty"`
}

func (x *ProtoPoint) Reset() {
	*x = ProtoPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_rest_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPoint) ProtoMessage() {}

func (x *ProtoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rest_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPoint.ProtoReflect.Descriptor instead.
func (*ProtoPoint) Descriptor() ([]byte, []int) {
	return file_admin_rest_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoPoint) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProtoPoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProtoPoint) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *ProtoPoint) GetRestID() uint64 {
	if x != nil {
		return x.RestID
	}
	return 0
}

type ErrorCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ErrorCode) Reset() {
	*x = ErrorCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_rest_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorCode) ProtoMessage() {}

func (x *ErrorCode) ProtoReflect() protoreflect.Message {
	mi := &file_admin_rest_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorCode.ProtoReflect.Descriptor instead.
func (*ErrorCode) Descriptor() ([]byte, []int) {
	return file_admin_rest_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorCode) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_admin_rest_proto_proto protoreflect.FileDescriptor

var file_admin_rest_proto_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x22, 0xab, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x66, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x52,
	0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x65, 0x73, 0x74, 0x49, 0x44, 0x22, 0x1b, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x32, 0xe2, 0x06, 0x0a, 0x15, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x1a, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x58,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x58, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x50, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x44, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x55, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x4d, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x49, 0x44, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x4b, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x44, 0x1a,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_rest_proto_proto_rawDescOnce sync.Once
	file_admin_rest_proto_proto_rawDescData = file_admin_rest_proto_proto_rawDesc
)

func file_admin_rest_proto_proto_rawDescGZIP() []byte {
	file_admin_rest_proto_proto_rawDescOnce.Do(func() {
		file_admin_rest_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_rest_proto_proto_rawDescData)
	})
	return file_admin_rest_proto_proto_rawDescData
}

var file_admin_rest_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_rest_proto_proto_goTypes = []interface{}{
	(*ProtoID)(nil),         // 0: protobuf_admin_rest.ProtoID
	(*ProtoImage)(nil),      // 1: protobuf_admin_rest.ProtoImage
	(*ProtoRestaurant)(nil), // 2: protobuf_admin_rest.ProtoRestaurant
	(*ProtoProduct)(nil),    // 3: protobuf_admin_rest.ProtoProduct
	(*ProtoPoint)(nil),      // 4: protobuf_admin_rest.ProtoPoint
	(*ErrorCode)(nil),       // 5: protobuf_admin_rest.ErrorCode
}
var file_admin_rest_proto_proto_depIdxs = []int32{
	2,  // 0: protobuf_admin_rest.RestaurantAdminWorker.CreateRestaurant:input_type -> protobuf_admin_rest.ProtoRestaurant
	2,  // 1: protobuf_admin_rest.RestaurantAdminWorker.UpdateRestaurant:input_type -> protobuf_admin_rest.ProtoRestaurant
	1,  // 2: protobuf_admin_rest.RestaurantAdminWorker.UpdateRestaurantImage:input_type -> protobuf_admin_rest.ProtoImage
	0,  // 3: protobuf_admin_rest.RestaurantAdminWorker.DeleteRestaurant:input_type -> protobuf_admin_rest.ProtoID
	3,  // 4: protobuf_admin_rest.RestaurantAdminWorker.CreateProduct:input_type -> protobuf_admin_rest.ProtoProduct
	3,  // 5: protobuf_admin_rest.RestaurantAdminWorker.UpdateProduct:input_type -> protobuf_admin_rest.ProtoProduct
	1,  // 6: protobuf_admin_rest.RestaurantAdminWorker.UpdateProductImage:input_type -> protobuf_admin_rest.ProtoImage
	0,  // 7: protobuf_admin_rest.RestaurantAdminWorker.DeleteProduct:input_type -> protobuf_admin_rest.ProtoID
	4,  // 8: protobuf_admin_rest.RestaurantAdminWorker.CreatePoint:input_type -> protobuf_admin_rest.ProtoPoint
	0,  // 9: protobuf_admin_rest.RestaurantAdminWorker.DeletePoint:input_type -> protobuf_admin_rest.ProtoID
	5,  // 10: protobuf_admin_rest.RestaurantAdminWorker.CreateRestaurant:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 11: protobuf_admin_rest.RestaurantAdminWorker.UpdateRestaurant:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 12: protobuf_admin_rest.RestaurantAdminWorker.UpdateRestaurantImage:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 13: protobuf_admin_rest.RestaurantAdminWorker.DeleteRestaurant:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 14: protobuf_admin_rest.RestaurantAdminWorker.CreateProduct:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 15: protobuf_admin_rest.RestaurantAdminWorker.UpdateProduct:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 16: protobuf_admin_rest.RestaurantAdminWorker.UpdateProductImage:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 17: protobuf_admin_rest.RestaurantAdminWorker.DeleteProduct:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 18: protobuf_admin_rest.RestaurantAdminWorker.CreatePoint:output_type -> protobuf_admin_rest.ErrorCode
	5,  // 19: protobuf_admin_rest.RestaurantAdminWorker.DeletePoint:output_type -> protobuf_admin_rest.ErrorCode
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_admin_rest_proto_proto_init() }
func file_admin_rest_proto_proto_init() {
	if File_admin_rest_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_rest_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_rest_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_rest_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoRestaurant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_rest_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_rest_proto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_rest_proto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_rest_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_rest_proto_proto_goTypes,
		DependencyIndexes: file_admin_rest_proto_proto_depIdxs,
		MessageInfos:      file_admin_rest_proto_proto_msgTypes,
	}.Build()
	File_admin_rest_proto_proto = out.File
	file_admin_rest_proto_proto_rawDesc = nil
	file_admin_rest_proto_proto_goTypes = nil
	file_admin_rest_proto_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RestaurantAdminWorkerClient is the client API for RestaurantAdminWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantAdminWorkerClient interface {
	CreateRestaurant(ctx context.Context, in *ProtoRestaurant, opts ...grpc.CallOption) (*ErrorCode, error)
	UpdateRestaurant(ctx context.Context, in *ProtoRestaurant, opts ...grpc.CallOption) (*ErrorCode, error)
	UpdateRestaurantImage(ctx context.Context, in *ProtoImage, opts ...grpc.CallOption) (*ErrorCode, error)
	DeleteRestaurant(ctx context.Context, in *ProtoID, opts ...grpc.CallOption) (*ErrorCode, error)
	CreateProduct(ctx context.Context, in *ProtoProduct, opts ...grpc.CallOption) (*ErrorCode, error)
	UpdateProduct(ctx context.Context, in *ProtoProduct, opts ...grpc.CallOption) (*ErrorCode, error)
	UpdateProductImage(ctx context.Context, in *ProtoImage, opts ...grpc.CallOption) (*ErrorCode, error)
	DeleteProduct(ctx context.Context, in *ProtoID, opts ...grpc.CallOption) (*ErrorCode, error)
	CreatePoint(ctx context.Context, in *ProtoPoint, opts ...grpc.CallOption) (*ErrorCode, error)
	DeletePoint(ctx context.Context, in *ProtoID, opts ...grpc.CallOption) (*ErrorCode, error)
}

type restaurantAdminWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantAdminWorkerClient(cc grpc.ClientConnInterface) RestaurantAdminWorkerClient {
	return &restaurantAdminWorkerClient{cc}
}

func (c *restaurantAdminWorkerClient) CreateRestaurant(ctx context.Context, in *ProtoRestaurant, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/CreateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) UpdateRestaurant(ctx context.Context, in *ProtoRestaurant, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/UpdateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) UpdateRestaurantImage(ctx context.Context, in *ProtoImage, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/UpdateRestaurantImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) DeleteRestaurant(ctx context.Context, in *ProtoID, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/DeleteRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) CreateProduct(ctx context.Context, in *ProtoProduct, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) UpdateProduct(ctx context.Context, in *ProtoProduct, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) UpdateProductImage(ctx context.Context, in *ProtoImage, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/UpdateProductImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) DeleteProduct(ctx context.Context, in *ProtoID, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) CreatePoint(ctx context.Context, in *ProtoPoint, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/CreatePoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantAdminWorkerClient) DeletePoint(ctx context.Context, in *ProtoID, opts ...grpc.CallOption) (*ErrorCode, error) {
	out := new(ErrorCode)
	err := c.cc.Invoke(ctx, "/protobuf_admin_rest.RestaurantAdminWorker/DeletePoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantAdminWorkerServer is the server API for RestaurantAdminWorker service.
type RestaurantAdminWorkerServer interface {
	CreateRestaurant(context.Context, *ProtoRestaurant) (*ErrorCode, error)
	UpdateRestaurant(context.Context, *ProtoRestaurant) (*ErrorCode, error)
	UpdateRestaurantImage(context.Context, *ProtoImage) (*ErrorCode, error)
	DeleteRestaurant(context.Context, *ProtoID) (*ErrorCode, error)
	CreateProduct(context.Context, *ProtoProduct) (*ErrorCode, error)
	UpdateProduct(context.Context, *ProtoProduct) (*ErrorCode, error)
	UpdateProductImage(context.Context, *ProtoImage) (*ErrorCode, error)
	DeleteProduct(context.Context, *ProtoID) (*ErrorCode, error)
	CreatePoint(context.Context, *ProtoPoint) (*ErrorCode, error)
	DeletePoint(context.Context, *ProtoID) (*ErrorCode, error)
}

// UnimplementedRestaurantAdminWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantAdminWorkerServer struct {
}

func (*UnimplementedRestaurantAdminWorkerServer) CreateRestaurant(context.Context, *ProtoRestaurant) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestaurant not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) UpdateRestaurant(context.Context, *ProtoRestaurant) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestaurant not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) UpdateRestaurantImage(context.Context, *ProtoImage) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestaurantImage not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) DeleteRestaurant(context.Context, *ProtoID) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestaurant not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) CreateProduct(context.Context, *ProtoProduct) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) UpdateProduct(context.Context, *ProtoProduct) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) UpdateProductImage(context.Context, *ProtoImage) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductImage not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) DeleteProduct(context.Context, *ProtoID) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) CreatePoint(context.Context, *ProtoPoint) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePoint not implemented")
}
func (*UnimplementedRestaurantAdminWorkerServer) DeletePoint(context.Context, *ProtoID) (*ErrorCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePoint not implemented")
}

func RegisterRestaurantAdminWorkerServer(s *grpc.Server, srv RestaurantAdminWorkerServer) {
	s.RegisterService(&_RestaurantAdminWorker_serviceDesc, srv)
}

func _RestaurantAdminWorker_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoRestaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/CreateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).CreateRestaurant(ctx, req.(*ProtoRestaurant))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_UpdateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoRestaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).UpdateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/UpdateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).UpdateRestaurant(ctx, req.(*ProtoRestaurant))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_UpdateRestaurantImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).UpdateRestaurantImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/UpdateRestaurantImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).UpdateRestaurantImage(ctx, req.(*ProtoImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_DeleteRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).DeleteRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/DeleteRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).DeleteRestaurant(ctx, req.(*ProtoID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).CreateProduct(ctx, req.(*ProtoProduct))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).UpdateProduct(ctx, req.(*ProtoProduct))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_UpdateProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).UpdateProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/UpdateProductImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).UpdateProductImage(ctx, req.(*ProtoImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).DeleteProduct(ctx, req.(*ProtoID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_CreatePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoPoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).CreatePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/CreatePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).CreatePoint(ctx, req.(*ProtoPoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantAdminWorker_DeletePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantAdminWorkerServer).DeletePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_admin_rest.RestaurantAdminWorker/DeletePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantAdminWorkerServer).DeletePoint(ctx, req.(*ProtoID))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestaurantAdminWorker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf_admin_rest.RestaurantAdminWorker",
	HandlerType: (*RestaurantAdminWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRestaurant",
			Handler:    _RestaurantAdminWorker_CreateRestaurant_Handler,
		},
		{
			MethodName: "UpdateRestaurant",
			Handler:    _RestaurantAdminWorker_UpdateRestaurant_Handler,
		},
		{
			MethodName: "UpdateRestaurantImage",
			Handler:    _RestaurantAdminWorker_UpdateRestaurantImage_Handler,
		},
		{
			MethodName: "DeleteRestaurant",
			Handler:    _RestaurantAdminWorker_DeleteRestaurant_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _RestaurantAdminWorker_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _RestaurantAdminWorker_UpdateProduct_Handler,
		},
		{
			MethodName: "UpdateProductImage",
			Handler:    _RestaurantAdminWorker_UpdateProductImage_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _RestaurantAdminWorker_DeleteProduct_Handler,
		},
		{
			MethodName: "CreatePoint",
			Handler:    _RestaurantAdminWorker_CreatePoint_Handler,
		},
		{
			MethodName: "DeletePoint",
			Handler:    _RestaurantAdminWorker_DeletePoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_rest_proto.proto",
}
