// Code generated by MockGen. DO NOT EDIT.
// Source: ../usecase.go

// Package mock_restaurants is a generated GoMock package.
package mock_restaurants

import (
	models "github.com/2020_1_Skycode/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetRestaurants mocks base method
func (m *MockUseCase) GetRestaurants(count, page, tagID uint64) ([]*models.Restaurant, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurants", count, page, tagID)
	ret0, _ := ret[0].([]*models.Restaurant)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRestaurants indicates an expected call of GetRestaurants
func (mr *MockUseCaseMockRecorder) GetRestaurants(count, page, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurants", reflect.TypeOf((*MockUseCase)(nil).GetRestaurants), count, page, tagID)
}

// GetRestaurantsRecommendations mocks base method
func (m *MockUseCase) GetRestaurantsRecommendations(userID, count uint64) ([]*models.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantsRecommendations", userID, count)
	ret0, _ := ret[0].([]*models.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantsRecommendations indicates an expected call of GetRestaurantsRecommendations
func (mr *MockUseCaseMockRecorder) GetRestaurantsRecommendations(userID, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantsRecommendations", reflect.TypeOf((*MockUseCase)(nil).GetRestaurantsRecommendations), userID, count)
}

// GetRestaurantByID mocks base method
func (m *MockUseCase) GetRestaurantByID(id uint64) (*models.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantByID", id)
	ret0, _ := ret[0].(*models.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantByID indicates an expected call of GetRestaurantByID
func (mr *MockUseCaseMockRecorder) GetRestaurantByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantByID", reflect.TypeOf((*MockUseCase)(nil).GetRestaurantByID), id)
}

// CreateRestaurant mocks base method
func (m *MockUseCase) CreateRestaurant(rest *models.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurant", rest)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRestaurant indicates an expected call of CreateRestaurant
func (mr *MockUseCaseMockRecorder) CreateRestaurant(rest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurant", reflect.TypeOf((*MockUseCase)(nil).CreateRestaurant), rest)
}

// UpdateRestaurant mocks base method
func (m *MockUseCase) UpdateRestaurant(rest *models.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", rest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant
func (mr *MockUseCaseMockRecorder) UpdateRestaurant(rest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockUseCase)(nil).UpdateRestaurant), rest)
}

// UpdateImage mocks base method
func (m *MockUseCase) UpdateImage(restID uint64, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", restID, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImage indicates an expected call of UpdateImage
func (mr *MockUseCaseMockRecorder) UpdateImage(restID, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockUseCase)(nil).UpdateImage), restID, filename)
}

// Delete mocks base method
func (m *MockUseCase) Delete(restID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", restID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUseCaseMockRecorder) Delete(restID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUseCase)(nil).Delete), restID)
}

// AddPoint mocks base method
func (m *MockUseCase) AddPoint(p *models.RestaurantPoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPoint", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPoint indicates an expected call of AddPoint
func (mr *MockUseCaseMockRecorder) AddPoint(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPoint", reflect.TypeOf((*MockUseCase)(nil).AddPoint), p)
}

// GetPoints mocks base method
func (m *MockUseCase) GetPoints(restID, count, page uint64) ([]*models.RestaurantPoint, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoints", restID, count, page)
	ret0, _ := ret[0].([]*models.RestaurantPoint)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPoints indicates an expected call of GetPoints
func (mr *MockUseCaseMockRecorder) GetPoints(restID, count, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoints", reflect.TypeOf((*MockUseCase)(nil).GetPoints), restID, count, page)
}

// GetRestaurantsInServiceRadius mocks base method
func (m *MockUseCase) GetRestaurantsInServiceRadius(address string, count, page, tagID uint64) ([]*models.Restaurant, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantsInServiceRadius", address, count, page, tagID)
	ret0, _ := ret[0].([]*models.Restaurant)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRestaurantsInServiceRadius indicates an expected call of GetRestaurantsInServiceRadius
func (mr *MockUseCaseMockRecorder) GetRestaurantsInServiceRadius(address, count, page, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantsInServiceRadius", reflect.TypeOf((*MockUseCase)(nil).GetRestaurantsInServiceRadius), address, count, page, tagID)
}

// GetRestaurantsRecommendationsInRadius mocks base method
func (m *MockUseCase) GetRestaurantsRecommendationsInRadius(address string, userID, count uint64) ([]*models.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantsRecommendationsInRadius", address, userID, count)
	ret0, _ := ret[0].([]*models.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantsRecommendationsInRadius indicates an expected call of GetRestaurantsRecommendationsInRadius
func (mr *MockUseCaseMockRecorder) GetRestaurantsRecommendationsInRadius(address, userID, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantsRecommendationsInRadius", reflect.TypeOf((*MockUseCase)(nil).GetRestaurantsRecommendationsInRadius), address, userID, count)
}

// AddReview mocks base method
func (m *MockUseCase) AddReview(review *models.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReview", review)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReview indicates an expected call of AddReview
func (mr *MockUseCaseMockRecorder) AddReview(review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReview", reflect.TypeOf((*MockUseCase)(nil).AddReview), review)
}

// GetReviews mocks base method
func (m *MockUseCase) GetReviews(restID, userID, count, page uint64) ([]*models.Review, *models.Review, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviews", restID, userID, count, page)
	ret0, _ := ret[0].([]*models.Review)
	ret1, _ := ret[1].(*models.Review)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetReviews indicates an expected call of GetReviews
func (mr *MockUseCaseMockRecorder) GetReviews(restID, userID, count, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviews", reflect.TypeOf((*MockUseCase)(nil).GetReviews), restID, userID, count, page)
}

// AddTag mocks base method
func (m *MockUseCase) AddTag(restID, tagID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", restID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTag indicates an expected call of AddTag
func (mr *MockUseCaseMockRecorder) AddTag(restID, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockUseCase)(nil).AddTag), restID, tagID)
}

// GetTags mocks base method
func (m *MockUseCase) GetTags(restID uint64) ([]*models.RestTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", restID)
	ret0, _ := ret[0].([]*models.RestTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags
func (mr *MockUseCaseMockRecorder) GetTags(restID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockUseCase)(nil).GetTags), restID)
}

// DeleteTag mocks base method
func (m *MockUseCase) DeleteTag(restID, tagID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", restID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag
func (mr *MockUseCaseMockRecorder) DeleteTag(restID, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockUseCase)(nil).DeleteTag), restID, tagID)
}

// GetProductTagsByID mocks base method
func (m *MockUseCase) GetProductTagsByID(restID uint64) ([]*models.ProductTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductTagsByID", restID)
	ret0, _ := ret[0].([]*models.ProductTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductTagsByID indicates an expected call of GetProductTagsByID
func (mr *MockUseCaseMockRecorder) GetProductTagsByID(restID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductTagsByID", reflect.TypeOf((*MockUseCase)(nil).GetProductTagsByID), restID)
}

// AddProductTag mocks base method
func (m *MockUseCase) AddProductTag(tag *models.ProductTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProductTag indicates an expected call of AddProductTag
func (mr *MockUseCaseMockRecorder) AddProductTag(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductTag", reflect.TypeOf((*MockUseCase)(nil).AddProductTag), tag)
}

// DeleteProductTag mocks base method
func (m *MockUseCase) DeleteProductTag(ID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductTag", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductTag indicates an expected call of DeleteProductTag
func (mr *MockUseCaseMockRecorder) DeleteProductTag(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductTag", reflect.TypeOf((*MockUseCase)(nil).DeleteProductTag), ID)
}
