// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package delivery

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8cdb472bDecodeGithubCom20201SkycodeInternalSessionsDelivery(in *jlexer.Lexer, out *signInRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "phone":
			out.Phone = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8cdb472bEncodeGithubCom20201SkycodeInternalSessionsDelivery(out *jwriter.Writer, in signInRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix[1:])
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v signInRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8cdb472bEncodeGithubCom20201SkycodeInternalSessionsDelivery(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v signInRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8cdb472bEncodeGithubCom20201SkycodeInternalSessionsDelivery(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *signInRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8cdb472bDecodeGithubCom20201SkycodeInternalSessionsDelivery(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *signInRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8cdb472bDecodeGithubCom20201SkycodeInternalSessionsDelivery(l, v)
}
func easyjson8cdb472bDecodeGithubCom20201SkycodeInternalSessionsDelivery1(in *jlexer.Lexer, out *SessionHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8cdb472bEncodeGithubCom20201SkycodeInternalSessionsDelivery1(out *jwriter.Writer, in SessionHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SessionHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8cdb472bEncodeGithubCom20201SkycodeInternalSessionsDelivery1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SessionHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8cdb472bEncodeGithubCom20201SkycodeInternalSessionsDelivery1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SessionHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8cdb472bDecodeGithubCom20201SkycodeInternalSessionsDelivery1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SessionHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8cdb472bDecodeGithubCom20201SkycodeInternalSessionsDelivery1(l, v)
}
