version: '3.3'
services:
  database:
    image: mdillon/postgis
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - ./database/database.env

volumes:
  pgdata:
