package tools

import "errors"

var (
	BadRequest                 = errors.New("Bad request")
	NoSuchUser                 = errors.New("Пользователь с данным именем не существует")
	WrongPassword              = errors.New("Неверный пароль")
	NotFound                   = errors.New("Не найдено")
	SessionStoreError          = errors.New("Store session error")
	NoSuchSession              = errors.New("Session cookie not found")
	DeleteSessionError         = errors.New("Error while deleting session")
	Unauthorized               = errors.New("Unauthorized")
	SessionTypeAssertionErr    = errors.New("Error assert to session type")
	UserTypeAssertionErr       = errors.New("Error assert to user type")
	UpdatePhoneError           = errors.New("Ошибка обновления номера телефона")
	DeleteAvatarError          = errors.New("Ошибка удаления аватара")
	CheckoutOrderError         = errors.New("Ошибка регистрации заказа")
	RestaurantNotFoundError    = errors.New("Ресторан не найден")
	RestaurantPermissionsError = errors.New("У вас недостаточно прав для управления данным рестораном")
	ExpiredCSRFError           = errors.New("Expired CSRF token")
	WrongCSRFtoken             = errors.New("Wrong CSRF token")
	CSRFNotPresented           = errors.New("CSRF not presented")
	HashingError               = errors.New("Ошибка хеширования")
	Authorized                 = errors.New("Вы уже авторизованы")
	NotRequiredFields          = errors.New("No such required fields")
	ErrorRequestValidation     = errors.New("Ошибка валидации")
	UserExists                 = errors.New("Данный номер телефона уже существует")
	GetOrdersError             = errors.New("Ошибка получения заказов")
	ReviewAlreadyExists        = errors.New("Вы уже оставили отзыв")
	BadQueryParams             = errors.New("Ошибка параметров запроса")
	ReviewNotFoundError        = errors.New("Отзыв не найден")
	PermissionError            = errors.New("У вас недостаточно прав")
	ApiResponseStatusNotOK     = errors.New("Ошибка овтета внешнего API")
	ApiAnswerEmptyResult       = errors.New("Некорректный ответ внешнего API")
	RestPointNotFound          = errors.New("Точка ресторана не найдена")
	ApiMultiAnswerError        = errors.New("Невозможно идентифицировать адрес")
	ApiNotHouseAnswerError     = errors.New("Выбранный адрес не является адресом дома")
	GRPCOpertionNotSuccess     = errors.New("GRPC answer not true, operation not success")
	ProductNotFoundError       = errors.New("Продукт не найден")
	BindingError               = errors.New("Error while binding request")
	RestTagNotFound            = errors.New("Тег ресторана не найден")
	TagRestComboAlreadyExist   = errors.New("Ресторан уже имеет данный тег")
	TagRestComboDoesntExist    = errors.New("Ресторан не имеет данного тега")
	ProductTagNotFound         = errors.New("Тег продукта не найден")
	UnknownOrderStatus         = errors.New("Неизвестный статус заказа")
	OrderNotFound              = errors.New("Заказ не найден")
	NewStatusIsTheSame         = errors.New("Новый статус заказа совпадает с текущим")
	NotificationNotFound       = errors.New("Уведомление не найдено")
	NoteConnectionExists       = errors.New("Веб-сокет соединение уже существует")
	ChatNotFound               = errors.New("Чат с данным id не найден")
	NewSupportJoinError        = errors.New("Невозможно подключить вас, пока текущий саппорт подключен к чату")
	ChatInUse                  = errors.New("Чат испольузется. Удаление запрещено")
	RestaurantNameExists       = errors.New("Ресторана с данным именем существует")
)
