// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package delivery

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9fe6ccc2DecodeGithubCom20201SkycodeInternalReviewsDelivery(in *jlexer.Lexer, out *reviewUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "text":
			out.Text = string(in.String())
		case "rate":
			out.Rate = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9fe6ccc2EncodeGithubCom20201SkycodeInternalReviewsDelivery(out *jwriter.Writer, in reviewUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"rate\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v reviewUpdateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9fe6ccc2EncodeGithubCom20201SkycodeInternalReviewsDelivery(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v reviewUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9fe6ccc2EncodeGithubCom20201SkycodeInternalReviewsDelivery(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *reviewUpdateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9fe6ccc2DecodeGithubCom20201SkycodeInternalReviewsDelivery(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *reviewUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9fe6ccc2DecodeGithubCom20201SkycodeInternalReviewsDelivery(l, v)
}
func easyjson9fe6ccc2DecodeGithubCom20201SkycodeInternalReviewsDelivery1(in *jlexer.Lexer, out *ReviewsHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9fe6ccc2EncodeGithubCom20201SkycodeInternalReviewsDelivery1(out *jwriter.Writer, in ReviewsHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewsHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9fe6ccc2EncodeGithubCom20201SkycodeInternalReviewsDelivery1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewsHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9fe6ccc2EncodeGithubCom20201SkycodeInternalReviewsDelivery1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewsHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9fe6ccc2DecodeGithubCom20201SkycodeInternalReviewsDelivery1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewsHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9fe6ccc2DecodeGithubCom20201SkycodeInternalReviewsDelivery1(l, v)
}
