// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository.go

// Package mock_geodata is a generated GoMock package.
package mock_geodata

import (
	models "github.com/2020_1_Skycode/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetGeoPosByAddress mocks base method
func (m *MockRepository) GetGeoPosByAddress(arg0 string) (*models.GeoPos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeoPosByAddress", arg0)
	ret0, _ := ret[0].(*models.GeoPos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeoPosByAddress indicates an expected call of GetGeoPosByAddress
func (mr *MockRepositoryMockRecorder) GetGeoPosByAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeoPosByAddress", reflect.TypeOf((*MockRepository)(nil).GetGeoPosByAddress), arg0)
}
