// Code generated by MockGen. DO NOT EDIT.
// Source: ../usecase.go

// Package mock_geodata is a generated GoMock package.
package mock_geodata

import (
	models "github.com/2020_1_Skycode/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CheckGeoPos mocks base method
func (m *MockUseCase) CheckGeoPos(address string) (*models.GeoPos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGeoPos", address)
	ret0, _ := ret[0].(*models.GeoPos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckGeoPos indicates an expected call of CheckGeoPos
func (mr *MockUseCaseMockRecorder) CheckGeoPos(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGeoPos", reflect.TypeOf((*MockUseCase)(nil).CheckGeoPos), address)
}
